//! Reads the real Start menu, its icons and its launches through the shell.

use std::error::Error;
use std::path::{Path, PathBuf};

use carronade::apps::{self, App};
use carronade::error::Error as CarronadeError;
use carronade::{icons, shell};

#[test]
fn list_finds_named_apps_in_name_order() -> Result<(), Box<dyn Error>> {
    let apps = apps::list()?;
    // Every account has at least the packaged apps Windows ships.
    assert!(!apps.is_empty());
    assert!(
        apps.iter()
            .all(|app| !app.name.is_empty() && !app.id.is_empty())
    );
    let names: Vec<String> = apps.iter().map(|app| app.name.to_lowercase()).collect();
    assert!(names.is_sorted());
    Ok(())
}

#[test]
fn list_includes_packaged_apps() -> Result<(), Box<dyn Error>> {
    // Packaged apps have an AUMID, family name then `!` then app id. Settings ships with every Windows 11 install.
    let apps = apps::list()?;
    assert!(apps.iter().any(|app| app.id.starts_with("windows.immersivecontrolpanel_") && app.id.contains('!')));
    Ok(())
}

/// `apps.toml` in an emptied folder `apps-<name>` for one test.
fn cache(name: &str) -> Result<PathBuf, Box<dyn Error>> {
    let folder = Path::new(env!("CARGO_TARGET_TMPDIR")).join(format!("apps-{name}"));
    if folder.exists() {
        std::fs::remove_dir_all(&folder)?;
    }
    std::fs::create_dir_all(&folder)?;
    Ok(folder.join("apps.toml"))
}

fn gadget() -> App {
    App {
        name: "Gadget".to_owned(),
        id: "Contoso.Gadget_0000000000000!App".to_owned(),
        exe: None,
    }
}

#[test]
fn a_saved_list_loads_back_with_its_exe_names() -> Result<(), Box<dyn Error>> {
    let path = cache("saved")?;
    let acme = App {
        name: "Acme Shell (x64)".to_owned(),
        id: "Acme.AutoGenerated.{A49227EA-5AF0-D494-A3F1-0918A278ED71}".to_owned(),
        exe: Some("acme".to_owned()),
    };
    let apps = vec![acme, gadget()];
    apps::save(&path, &apps)?;
    assert_eq!(apps::load(&path)?, Some(apps));
    Ok(())
}

#[test]
fn an_app_without_exe_loads_with_none() -> Result<(), Box<dyn Error>> {
    let path = cache("no-exe")?;
    std::fs::write(
        &path,
        "[[app]]\nname = \"Gadget\"\nid = \"Contoso.Gadget_0000000000000!App\"\n",
    )?;
    assert_eq!(apps::load(&path)?, Some(vec![gadget()]));
    Ok(())
}

#[test]
fn a_missing_cache_loads_as_none() -> Result<(), Box<dyn Error>> {
    assert_eq!(apps::load(&cache("missing")?)?, None);
    Ok(())
}

#[test]
fn an_invalid_cache_names_its_path() -> Result<(), Box<dyn Error>> {
    let path = cache("invalid")?;
    std::fs::write(&path, "[[app]]\nname = \"Only a name\"\n")?;
    let result = apps::load(&path);
    assert!(
        matches!(&result, Err(CarronadeError::StoreParse { path: failed, .. }) if *failed == path),
        "got {result:?}"
    );
    Ok(())
}

#[test]
fn every_app_has_an_icon() -> Result<(), Box<dyn Error>> {
    for app in apps::list()? {
        icons::display_icon(&app.target(), 32)?;
    }
    Ok(())
}

#[test]
fn a_missing_app_is_no_item() {
    let target = "shell:AppsFolder\\carronade.missing_0000000000000!App";
    let result = icons::icon(target, 32);
    assert!(
        matches!(&result, Err(CarronadeError::NoItem { target: failed, .. }) if failed == target),
        "got {result:?}"
    );
}

#[test]
fn launching_a_missing_app_names_it_in_the_error() {
    let target = "shell:AppsFolder\\carronade.missing_0000000000000!App";
    let result = shell::launch(target);
    assert!(
        matches!(&result, Err(CarronadeError::Launch { target: failed, .. }) if failed == target),
        "got {result:?}"
    );
}

#[test]
fn launching_a_missing_app_as_admin_names_it_in_the_error() {
    let target = "shell:AppsFolder\\carronade.missing_0000000000000!App";
    let result = shell::launch_as_admin(target);
    assert!(
        matches!(&result, Err(CarronadeError::Launch { target: failed, .. }) if failed == target),
        "got {result:?}"
    );
}
